#!/bin/bash
# =============================================================================
# Snort 3 Community Rules Setup Script
# =============================================================================
# Downloads Snort 3 community rules and creates a minimal configuration
# for running Snort as an IDS on the controller machine.
#
# Usage:  sudo bash snort_setup.sh [INTERFACE] [HOME_NET]
# Example: sudo bash snort_setup.sh ens33 10.0.0.0/24
# Example (multi-network): sudo bash snort_setup.sh eth0 "10.0.0.0/24,192.168.1.0/24"
# =============================================================================

set -e

# ---- Configuration ----
INTERFACE="${1:-ens33}"
# Default: Mininet (10.0.0.x) + management (192.168.1.x) for controller+Mininet-wifi setup
HOME_NET_RAW="${2:-10.0.0.0/24,192.168.1.0/24}"

# Format HOME_NET for Snort 3: multiple networks need brackets [a,b,c]
if echo "${HOME_NET_RAW}" | grep -q ','; then
    HOME_NET="[${HOME_NET_RAW}]"
else
    HOME_NET="${HOME_NET_RAW}"
fi
RULES_URL="https://www.snort.org/downloads/community/snort3-community-rules.tar.gz"
SNORT_DIR="/etc/snort"
RULES_DIR="${SNORT_DIR}/rules"
LOG_DIR="/var/log/snort"
CONF_FILE="${SNORT_DIR}/snort.lua"
TARBALL="/tmp/snort3-community-rules.tar.gz"

echo "=============================================="
echo "  Snort 3 Community Rules Setup"
echo "=============================================="
echo "  Interface : ${INTERFACE}"
echo "  HOME_NET  : ${HOME_NET}"
echo "=============================================="

# ---- Pre-flight checks ----
if [ "$EUID" -ne 0 ]; then
    echo "ERROR: This script must be run as root (sudo)."
    exit 1
fi

# Check if Snort 3 is installed
if ! command -v snort &> /dev/null; then
    echo "ERROR: Snort 3 is not installed."
    echo "Install it with:  sudo apt install snort  (or build from source)"
    echo "See: https://www.snort.org/downloads"
    exit 1
fi

SNORT_VER=$(snort -V 2>&1 | head -5)
echo ""
echo "Snort version detected:"
echo "${SNORT_VER}"
echo ""

# Check interface exists
if ! ip link show "${INTERFACE}" &> /dev/null; then
    echo "WARNING: Interface '${INTERFACE}' not found. Available interfaces:"
    ip -br link show
    echo ""
    echo "You can re-run with: sudo bash snort_setup.sh <interface> <home_net>"
fi

# ---- Step 1: Create directories ----
echo "[1/5] Creating directories..."
mkdir -p "${RULES_DIR}"
mkdir -p "${LOG_DIR}"

# ---- Step 2: Download community rules ----
echo "[2/5] Downloading Snort 3 community rules..."
if command -v wget &> /dev/null; then
    wget -q --show-progress -O "${TARBALL}" "${RULES_URL}"
elif command -v curl &> /dev/null; then
    curl -L -o "${TARBALL}" "${RULES_URL}"
else
    echo "ERROR: Neither wget nor curl is available. Install one and retry."
    exit 1
fi

echo "    Downloaded: ${TARBALL}"

# ---- Step 3: Extract rules ----
echo "[3/5] Extracting community rules..."
tar -xzf "${TARBALL}" -C /tmp/

# The archive extracts to snort3-community-rules/ containing snort3-community.rules
if [ -f "/tmp/snort3-community-rules/snort3-community.rules" ]; then
    cp /tmp/snort3-community-rules/snort3-community.rules "${RULES_DIR}/"
    echo "    Rules extracted to: ${RULES_DIR}/snort3-community.rules"
else
    echo "ERROR: Expected rules file not found in archive."
    echo "    Contents of /tmp/snort3-community-rules/:"
    ls -la /tmp/snort3-community-rules/ 2>/dev/null || echo "    (directory not found)"
    # Try to find .rules files
    FOUND_RULES=$(find /tmp/ -name "*.rules" -newer "${TARBALL}" 2>/dev/null | head -5)
    if [ -n "${FOUND_RULES}" ]; then
        echo "    Found rules files:"
        echo "${FOUND_RULES}"
        echo "    Copying first found rules file..."
        cp $(echo "${FOUND_RULES}" | head -1) "${RULES_DIR}/snort3-community.rules"
    else
        exit 1
    fi
fi

# Also copy the sid-msg.map if present
if [ -f "/tmp/snort3-community-rules/sid-msg.map" ]; then
    cp /tmp/snort3-community-rules/sid-msg.map "${RULES_DIR}/"
fi

RULE_COUNT=$(grep -c "^alert\|^drop\|^reject\|^pass" "${RULES_DIR}/snort3-community.rules" 2>/dev/null || echo "0")
echo "    Total rules loaded: ${RULE_COUNT}"

# ---- Step 4: Create Snort configuration ----
echo "[4/5] Creating Snort configuration..."

cat > "${CONF_FILE}" << 'SNORT_LUA_EOF'
-- =============================================================================
-- Snort 3 Configuration for SDN Controller IDS
-- =============================================================================
-- Auto-generated by snort_setup.sh
-- This configuration loads community rules and outputs alerts in alert_fast
-- format for parsing by the SDN controller's SnortMonitor.
-- =============================================================================

-- ---- Home Network Definition ----
HOME_NET = 'PLACEHOLDER_HOME_NET'
EXTERNAL_NET = '!$HOME_NET'

-- ---- Decoder settings ----
ips =
{
    -- Enable built-in rules and community rules
    enable_builtin_rules = true,
    include = BUILTIN_RULE_PATH,
    rules = [[
        include /etc/snort/rules/snort3-community.rules
    ]]
}

-- ---- Inspection / Detection ----
-- Enable common inspectors for better detection
stream = { }
stream_tcp = { }
stream_udp = { }
stream_icmp = { }

-- HTTP inspector for web attack detection (SQL injection, XSS, etc.)
http_inspect = { }

-- Normalize payloads
normalizer = { tcp = { ips = true } }

-- ---- Alert Output ----
-- Use alert_fast for easy parsing by the Python monitor
alert_fast =
{
    file = true,
    packet = false,
}

-- ---- Logging ----
-- Ensure output goes to the configured log directory
output =
{
    event_trace = { max_data = 0 },
}
SNORT_LUA_EOF

# Replace placeholder with actual HOME_NET
sed -i "s|PLACEHOLDER_HOME_NET|${HOME_NET}|g" "${CONF_FILE}"

echo "    Configuration written to: ${CONF_FILE}"

# ---- Step 5: Validate configuration ----
echo "[5/5] Validating Snort configuration..."
echo ""

# Try validation (may produce warnings which are OK)
if snort -c "${CONF_FILE}" --warn-all -Q 2>&1 | tail -20; then
    echo ""
    echo "=============================================="
    echo "  ✅ Snort 3 setup complete!"
    echo "=============================================="
else
    echo ""
    echo "=============================================="
    echo "  ⚠️  Snort configuration may have issues."
    echo "  Check the warnings above."
    echo "  You may need to adjust ${CONF_FILE}"
    echo "=============================================="
fi

# ---- Cleanup ----
rm -f "${TARBALL}"
rm -rf /tmp/snort3-community-rules/

echo ""
echo "To start Snort manually (test):"
echo "  sudo snort -c ${CONF_FILE} -i ${INTERFACE} -l ${LOG_DIR} -A alert_fast"
echo ""
echo "To use with the SDN controller, just start the controller:"
echo "  sudo ryu-manager Controller/Controller\\ network\\ only\\ .py"
echo ""
echo "Snort will be started automatically by the controller's SnortMonitor."
echo ""
